### ISSUE TITLE
About RenderDebug

### ISSUE THREAD

**Issue by skymen** [Straskal/MonoReaper#14]
Hey!

Sorry for posting this here, I couldn't find any other way to contact you. I have fixed and updated your RenderDebug Construct 3 addon and added MeshPoly drawing.

[renderbug-1.2.2.0-stable.zip](https://github.com/Straskal/MonoReaper/files/13698296/renderbug-1.2.2.0-stable.zip)

Can you please upload this new version?
You can delete this issue whenever you want 👍 

I plan on making a similar addon in the future so I will not keep bothering you with fixes. I just figured since for now it's the only option we have for debug rendering, it would be nice to at least have the addon work.

**Comment by Straskal** [comment]
@skymen No problemo. I appreciate you making that fix! I've unarchived the original repository https://github.com/Straskal/c3addons

Please create a branch / PR into master in that repository. I'll review / merge the changes before re-uploading the addon to construct's site.

Thank you!

**Comment by skymen** [comment]
Thanks! Done https://github.com/Straskal/c3addons/pull/13
